### ISSUE TITLE
[#1] Configurar github pages 

### ISSUE THREAD

**Issue by jps12** [UnBArqDsw2020-2/2020.2_G2_Encare#1]
## Tarefas

Para disponibilização dos artefatos gerados durante o semestre é necessário a criação de um github pages que possa ser organizado e também que gere a páina automaticamente a partir de um documento markdown. A ferramenta a ser utilizada é o mkdocs

## Descrição
- [x] mkdocs configurado no repositório.
- [x] Link disponível para acesso.

**Comment by nicaloribeiro** [comment]
https://unbarqdsw2020-2.github.io/2020.2_G2_Encare/

**Comment by nicaloribeiro** [comment]
Links com temas para o pages :  
[MkDocs Themes](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes)    
[Bootstrap Theme](https://mkdocs.github.io/mkdocs-bootstrap/)

**Comment by nicaloribeiro** [comment]
O mkdocs será configurado a partir da branch develop.

**Comment by jps12** [comment]
Pull request #27 aceito
