### ISSUE TITLE
[#20] Primeira Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBArqDsw2020-2/2020.2_G2_Encare#20]
## Descrição

Olá Pessoal!

O Grupo 02 irá avaliar o Grupo 03 nessa primeira avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta entrar no Tópico 2 DSW(Base) da trilha do Moodle, e procurar por "Primeira Avaliação por Pares".

Atenciosamente.

**Comment by jps12** [comment]
A avaliação ja foi feita e foi entregue
