### ISSUE TITLE
[#22] Refatorar documentos

### ISSUE THREAD

**Issue by jps12** [UnBArqDsw2020-2/2020.2_G2_Encare#22]
## Descrição

Alguns documentos que ja estão na develop estão com os links das imagens quebrados, pois os links são da branch onde foi feito o documento. Além disso revisar ortografia.

## Tarefas
- [x] As imagens estão visíveis no git pages também.
- [x] As imagens estão em tamanho padrão e centralizadas
- [x] Corrigir erros de português nos documentos existentes

**Comment by baraky** [comment]
Qual seria o tamanho padrão das imagens?

**Comment by nicaloribeiro** [comment]
> Qual seria o tamanho padrão das imagens?

@baraky Acho que não precisa ter um tamanho padrão. Só referenciar e deixar o tamanho que o markdown/mkdocs colocar.

**Comment by nicaloribeiro** [comment]
Acho que é necessário esperar a conclusão dos documentos da sprint para poder organizar os documentos e construir o github pages.

**Comment by jps12** [comment]
Pull request #50 aceito
