### ISSUE TITLE
[#34] Diagrama de atividades

### ISSUE THREAD

**Issue by jps12** [UnBArqDsw2020-2/2020.2_G2_Encare#34]
## Descrição:

Elaborar diagrama de atividades que demonstre graficamente as atividades possíveis dentro do sistema.

## Tarefas:

- [x] Diagrama criado.

## Revisores:

**Comment by codehg** [comment]
Tudo certo, amanhã farei uma revisão para prosseguir com o PR

**Comment by jps12** [comment]
#41 Pull request aceito
