### ISSUE TITLE
[#35] Configurar ambiente de programação 

### ISSUE THREAD

**Issue by jps12** [UnBArqDsw2020-2/2020.2_G2_Encare#35]
## Descrição

Deverá se configurar um ambiente de desenvolvimento a fim de evitar possíveis problemas de compatibilidade entre os membros da equipe.

## Tarefas:

- [x] Docker do frontend criado e funcionando.
- [x] Docker do backend criado e funcionando.
- [x] Criado um repositório para hospedar o frontend da aplicação

## Revisor(es):
@nicaloribeiro

**Comment by satsfy** [comment]
Issue completa

**Comment by jps12** [comment]
pull request #53 aceito
