### ISSUE TITLE
[#36] Protótipo de alta fidelidade

### ISSUE THREAD

**Issue by jps12** [UnBArqDsw2020-2/2020.2_G2_Encare#36]
## Descrição 

Adicionar as telas de login e cadastro ao protótipo de alta fidelidade. ALém disso sugere ser criada como fica a tela do perfil do estabelecimento se o usuário for um admin e se ele for um owner. 

## Tarefas

- [x] Tela de login criada
- [x] Tela de cadastro criada
- [x] Adicionada alterações possíveis no layout em diferentes tipos de usuários.

**Comment by jps12** [comment]
#61 Foi aceito mas a isseu vai ficar aberta para conclusão da issue

**Comment by jps12** [comment]
> #61 Foi aceito mas a isseu vai ficar aberta para conclusão da issue

Como foi dito nesse comentário, a issue ficará aberta e com algumas modificações ja colocadas.

**Comment by codehg** [comment]
Finalizado
