### ISSUE TITLE
[#39] Documentar requisitos

### ISSUE THREAD

**Issue by nicaloribeiro** [UnBArqDsw2020-2/2020.2_G2_Encare#39]
# Descrição  

Após reuniões e e conversas do grupo, constatou-se que os requisitos do sistema não estavam devidamente documentados. Concluiu-se que é  importante documentar  os requisitos para o andamento correto do projeto.   

 # Tarefas  
- [x] Documentar os requisitos que já foram estabelecidos anteriormente;
- [x] Documentar novos requisitos com pelo menos mais uma técnica;
- [x] Separar os requisitos em funcionais e não funcionais.

**Comment by codehg** [comment]
Observar o acordo do documento de Contribuição, a Issue deve obedecer a estrutura acordada :)
