### ISSUE TITLE
[#59] Estudar padrões emergentes

### ISSUE THREAD

**Issue by jps12** [UnBArqDsw2020-2/2020.2_G2_Encare#59]
## Descrição:

Deverá pesquisar, estudar, analisar e documentar padrões emergentes mais relevantes, e aplicar no projeto em curso.

## Tarefas:

- [x] Pesquisar padrões de projetos emergentes relevantes. (todos).

**Comment by satsfy** [comment]
Não acredito que serverless seja um "padrão de arquitetura emergente" no sentido que esta issue pede, mas é, com certeza, um padrão emergente que poderíamos usar para aprender e para diminuir qualquer possível custo de hospedagem.  

Poderíamos usar um framework como o [serverless](https://www.serverless.com/) para implementar diversas [funções lambdas](https://docs.aws.amazon.com/lambda/latest/dg/welcome.html) sem fazer nenhuma manutenção de instancias. Aqui temos um vídeo comentando sobre alguns [padrões de arquitetura voltados ao serverless](https://youtu.be/TuZZIGSbFfQ). 

Embora o tópico seja fora do escopo da matéria (ou do escopo de qualquer matéria que não seja focada nisso) é uma arquitetura interessante e que está vindo a ser usada cada vez mais com o fim de cortar custos e facilitar implementação de microsserviços.

**Comment by jps12** [comment]
Pull request #66 aceito
