### ISSUE TITLE
Terceira Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBArqDsw2020-2/2020.2_G2_Encare#72]
Olá Pessoal!

O Grupo 02 irá avaliar o Grupo 04 nessa terceira avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta entrar no Tópico 2 DSW(Padrões de Projeto) da trilha do Moodle, e procurar por "Terceira Avaliação por Pares".

Atenciosamente.

**Comment by jps12** [comment]
Avaliação por pares ja foi feita
