### ISSUE TITLE
[#9] Elaborar documento de metodologia.

### ISSUE THREAD

**Issue by jps12** [UnBArqDsw2020-2/2020.2_G2_Encare#9]
## Descrição

Elaborar um documento que explique a metodologia a ser usada no processo de criação e evolução do software.

## Tarefas

- [x] Esteja explicado toda a metodologia a ser aplicada no projeto.
- [x] Seja apresentada todas as ferramentas a serem usadas pela equipe.

**Comment by baraky** [comment]
Issue concluida no PR #13.
